import psutil, datetime
ram=psutil.virtual_memory()
total = ram.total / (1024 ** 3)
battery = psutil.sensors_battery()
available = ram.available / (1024 ** 3)
boot = psutil.boot_time()
print("Porcentaje de CPU usado:" , psutil.cpu_percent(interval=1))
print("-------------")
print("Cantidad total de RAM:" , total,"GB")
print("-------------")
print("RAM disponible:" , available,"GB")
print("-------------")
print("Porcentaje de RAM usada:" , ram.percent,"%")
print("-------------")
print("Porcentaje de batería:" , battery.percent, "%" )
print("-------------")
print("¿Se está cargando el dispositivo?:" , battery.power_plugged)
print("-------------")
print("Fecha de arranque del dispositivo: ")
print(datetime.datetime.fromtimestamp(boot))
